### ISSUE TITLE
途中から再生

### ISSUE THREAD

**Issue by YoshikawaMasashi** [yos1up/mimicOpus#12]

**Comment by yos1up** [comment]
問題が音声ファイル化されてない現状だと実は対応しづらい（再生開始位置の手前から鳴り続けているはずのノーツが再生されないので，耳コピしやすくなってしまう）

**Comment by toslunar** [comment]
解答の方を途中から途中まで再生できる機能がまずほしいです。
（現状，別窓の1小節目に打ち込んだりしてます……。）

**Comment by YoshikawaMasashi** [comment]
> （再生開始位置の手前から鳴り続けているはずのノーツが再生されないので，耳コピしやすくなってしまう）
とりあえず、これは技術的困難から後回しにして、４拍ごとに途中から（問題も回答も）再生できるようにしました。
