### ISSUE TITLE
公式twitterへのリンク

### ISSUE THREAD

**Issue by yos1up** [yos1up/mimicOpus#122]
トップページに

**Comment by YoshikawaMasashi** [comment]
https://github.com/saurabhnemade/react-twitter-embed#readme
これを使えば一瞬ぽい

**Comment by YoshikawaMasashi** [comment]
上はなんとなく怪しいので、公式でやるのはあり
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview

**Comment by YoshikawaMasashi** [comment]
上はなんとなく怪しいので、公式でやるのはあり
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview

**Comment by YoshikawaMasashi** [comment]
[test.txt](https://github.com/yos1up/mimicOpus/files/2578506/test.txt)

**Comment by YoshikawaMasashi** [comment]
Done.
