### ISSUE TITLE
CDE表記は人によってはわかりづらいかも

### ISSUE THREAD

**Issue by YoshikawaMasashi** [yos1up/mimicOpus#138]

**Comment by yos1up** [comment]
「ドレミ」あるいは鍵盤の図を表示？

**Comment by loloiccl** [comment]
個人的には五線譜へ採譜していく形式があると嬉しいですが、実装が難しそう。

@yos1up 個人的にはドレミは移動ドのイメージもあるので、断りなく使って良い表記では無いと思います。
(断りを入れるなら、結局イロハか CDE か 440Hz が登場するのが難しいですが)

**Comment by yos1up** [comment]
五線譜，おっしゃる通り実装は結構手間に思います．ニーズの大きさ次第では・・・という感じでしょうか．（個人的な話ですが自分もDTMの打ち込みは五線譜モードを使うことが多いです）

「鍵盤の図を表示」は，こんな感じをイメージしての提案です．
http://www.oliphaunts.com/pianoroll-js/

**Comment by YoshikawaMasashi** [comment]
鍵盤を表示を実装しました。
五線譜も今後実装するかもです。
#191
