### ISSUE TITLE
満点をとっていない問題の検索

### ISSUE THREAD

**Issue by y2usagi** [yos1up/mimicOpus#167]
「回答済み (提出したことがある) だけど、満点をとっていない問題」が検索しやすいと嬉しいです。

純粋に各項目ソートできるようにするでもよいのかもしれません。
(「回答済み」で絞って自分のスコアの昇順にソートすればよくなるので)

**Comment by YoshikawaMasashi** [comment]
こちら、需要がありそうなので、今週か来週に対応しますね。

**Comment by YoshikawaMasashi** [comment]
満点を取っているかどうかのフィルターで実装しました。
検索クエリ等については
#192　で再検討しましょう。
