### ISSUE TITLE
鍵盤押し直しが分かりにくくなった

### ISSUE THREAD

**Issue by toslunar** [yos1up/mimicOpus#194]
<img width="599" alt="screen shot 2018-12-30 at 22 08 36" src="https://user-images.githubusercontent.com/1964281/50547580-957eb600-0c7f-11e9-8691-047fe489879e.png">

**Comment by YoshikawaMasashi** [comment]
![image](https://user-images.githubusercontent.com/17809477/50554790-cead3980-0d04-11e9-81b7-6ebf6b2676f6.png)
これでどうでしょうか？

**Comment by YoshikawaMasashi** [comment]
hotfix出しました
