### ISSUE TITLE
初めてサインインした時のデフォルト名前設定は anonymous よりGoogleアカウント名そのままの方が良い？

### ISSUE THREAD

**Issue by yos1up** [yos1up/mimicOpus#98]

**Comment by YoshikawaMasashi** [comment]
一意なusernameと一意じゃないdisplaynameを用意する
displaynameにアカウント名を入れる
usernameはとりあえずnullを入れて、alphaversionでは使わないので、そのままにしておく。
betaでusernameをユーザーが設定するようにする。（usernameは一度設定したら変えられないようにする

**Comment by yos1up** [comment]
プロフィール画面ではdisplaynameを編集可にするんですか？

**Comment by YoshikawaMasashi** [comment]
そうですね。アルファばんではdisplaynameだけを使います。

usernameの方はアルファ版では使いませんので、
ベータ版ではusernameが決まってない人だけに、usernameを決める画面をつけようかと思っています。

**Comment by YoshikawaMasashi** [comment]
Done.
